/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Request of setting status for alerts
 */
@ApiModel(description = "Request of setting status for alerts")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class AlertSetStatusRequest {
  @SerializedName("alertHistoryIds")
  private List<Long> alertHistoryIds = new ArrayList<Long>();

  @SerializedName("status")
  private String status = null;

  public AlertSetStatusRequest alertHistoryIds(List<Long> alertHistoryIds) {
    this.alertHistoryIds = alertHistoryIds;
    return this;
  }

  public AlertSetStatusRequest addAlertHistoryIdsItem(Long alertHistoryIdsItem) {
    this.alertHistoryIds.add(alertHistoryIdsItem);
    return this;
  }

   /**
   * Alert history ids to set status
   * @return alertHistoryIds
  **/
  @ApiModelProperty(required = true, value = "Alert history ids to set status")
  public List<Long> getAlertHistoryIds() {
    return alertHistoryIds;
  }

  public void setAlertHistoryIds(List<Long> alertHistoryIds) {
    this.alertHistoryIds = alertHistoryIds;
  }

  public AlertSetStatusRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of alerts, classified as read or unread
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of alerts, classified as read or unread")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertSetStatusRequest alertSetStatusRequest = (AlertSetStatusRequest) o;
    return Objects.equals(this.alertHistoryIds, alertSetStatusRequest.alertHistoryIds) &&
        Objects.equals(this.status, alertSetStatusRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alertHistoryIds, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertSetStatusRequest {\n");
    
    sb.append("    alertHistoryIds: ").append(toIndentedString(alertHistoryIds)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

