/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Request of cancelling cloudscan jobs
 */
@ApiModel(description = "Request of cancelling cloudscan jobs")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class CloudJobCancelRequest {
  @SerializedName("jobTokens")
  private List<String> jobTokens = new ArrayList<String>();

  public CloudJobCancelRequest jobTokens(List<String> jobTokens) {
    this.jobTokens = jobTokens;
    return this;
  }

  public CloudJobCancelRequest addJobTokensItem(String jobTokensItem) {
    this.jobTokens.add(jobTokensItem);
    return this;
  }

   /**
   * List containing single cloud job token to cancel
   * @return jobTokens
  **/
  @ApiModelProperty(required = true, value = "List containing single cloud job token to cancel")
  public List<String> getJobTokens() {
    return jobTokens;
  }

  public void setJobTokens(List<String> jobTokens) {
    this.jobTokens = jobTokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudJobCancelRequest cloudJobCancelRequest = (CloudJobCancelRequest) o;
    return Objects.equals(this.jobTokens, cloudJobCancelRequest.jobTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobTokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudJobCancelRequest {\n");
    
    sb.append("    jobTokens: ").append(toIndentedString(jobTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

