/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IidMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class IidMapping {
  @SerializedName("fromIid")
  private String fromIid = null;

  @SerializedName("toIid")
  private String toIid = null;

  public IidMapping fromIid(String fromIid) {
    this.fromIid = fromIid;
    return this;
  }

   /**
   * Get fromIid
   * @return fromIid
  **/
  @ApiModelProperty(value = "")
  public String getFromIid() {
    return fromIid;
  }

  public void setFromIid(String fromIid) {
    this.fromIid = fromIid;
  }

  public IidMapping toIid(String toIid) {
    this.toIid = toIid;
    return this;
  }

   /**
   * Get toIid
   * @return toIid
  **/
  @ApiModelProperty(value = "")
  public String getToIid() {
    return toIid;
  }

  public void setToIid(String toIid) {
    this.toIid = toIid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IidMapping iidMapping = (IidMapping) o;
    return Objects.equals(this.fromIid, iidMapping.fromIid) &&
        Objects.equals(this.toIid, iidMapping.toIid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromIid, toIid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IidMapping {\n");
    
    sb.append("    fromIid: ").append(toIndentedString(fromIid)).append("\n");
    sb.append("    toIid: ").append(toIndentedString(toIid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

