/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Issue aging group object contains definition of project version attribute that can be used for issue aging table grouping.
 */
@ApiModel(description = "Issue aging group object contains definition of project version attribute that can be used for issue aging table grouping.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class IssueAgingGroupDto {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

   /**
   * ID of issue aging table grouping attribute. This ID should be passed to issue aging endpoint to return issue aging items that belongs only to this group
   * @return id
  **/
  @ApiModelProperty(required = true, value = "ID of issue aging table grouping attribute. This ID should be passed to issue aging endpoint to return issue aging items that belongs only to this group")
  public String getId() {
    return id;
  }

   /**
   * Name of the group to display it on UI.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the group to display it on UI.")
  public String getName() {
    return name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueAgingGroupDto issueAgingGroupDto = (IssueAgingGroupDto) o;
    return Objects.equals(this.id, issueAgingGroupDto.id) &&
        Objects.equals(this.name, issueAgingGroupDto.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueAgingGroupDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

