/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Request of cancelling jobs
 */
@ApiModel(description = "Request of cancelling jobs")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class JobCancelRequest {
  @SerializedName("jobIds")
  private List<String> jobIds = new ArrayList<String>();

  public JobCancelRequest jobIds(List<String> jobIds) {
    this.jobIds = jobIds;
    return this;
  }

  public JobCancelRequest addJobIdsItem(String jobIdsItem) {
    this.jobIds.add(jobIdsItem);
    return this;
  }

   /**
   * List containing single job ID to cancel
   * @return jobIds
  **/
  @ApiModelProperty(required = true, value = "List containing single job ID to cancel")
  public List<String> getJobIds() {
    return jobIds;
  }

  public void setJobIds(List<String> jobIds) {
    this.jobIds = jobIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobCancelRequest jobCancelRequest = (JobCancelRequest) o;
    return Objects.equals(this.jobIds, jobCancelRequest.jobIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobCancelRequest {\n");
    
    sb.append("    jobIds: ").append(toIndentedString(jobIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

