/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Job priority change information
 */
@ApiModel(description = "Job priority change information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class JobPriorityChangeInfo {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("jobClassName")
  private String jobClassName = null;

   /**
   * Number of the warnings of for the specific job class.
   * @return count
  **/
  @ApiModelProperty(required = true, value = "Number of the warnings of for the specific job class.")
  public Integer getCount() {
    return count;
  }

   /**
   * Job class name.
   * @return jobClassName
  **/
  @ApiModelProperty(required = true, value = "Job class name.")
  public String getJobClassName() {
    return jobClassName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobPriorityChangeInfo jobPriorityChangeInfo = (JobPriorityChangeInfo) o;
    return Objects.equals(this.count, jobPriorityChangeInfo.count) &&
        Objects.equals(this.jobClassName, jobPriorityChangeInfo.jobClassName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, jobClassName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobPriorityChangeInfo {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    jobClassName: ").append(toIndentedString(jobClassName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

