/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Request of assigning auth entity to project version
 */
@ApiModel(description = "Request of assigning auth entity to project version")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class ProjectVersionAuthEntityAssignRequest {
  @SerializedName("projectVersionIds")
  private List<Long> projectVersionIds = new ArrayList<Long>();

  public ProjectVersionAuthEntityAssignRequest projectVersionIds(List<Long> projectVersionIds) {
    this.projectVersionIds = projectVersionIds;
    return this;
  }

  public ProjectVersionAuthEntityAssignRequest addProjectVersionIdsItem(Long projectVersionIdsItem) {
    this.projectVersionIds.add(projectVersionIdsItem);
    return this;
  }

   /**
   * Project version ids to assign auth entity
   * @return projectVersionIds
  **/
  @ApiModelProperty(required = true, value = "Project version ids to assign auth entity")
  public List<Long> getProjectVersionIds() {
    return projectVersionIds;
  }

  public void setProjectVersionIds(List<Long> projectVersionIds) {
    this.projectVersionIds = projectVersionIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectVersionAuthEntityAssignRequest projectVersionAuthEntityAssignRequest = (ProjectVersionAuthEntityAssignRequest) o;
    return Objects.equals(this.projectVersionIds, projectVersionAuthEntityAssignRequest.projectVersionIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectVersionIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectVersionAuthEntityAssignRequest {\n");
    
    sb.append("    projectVersionIds: ").append(toIndentedString(projectVersionIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

