/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.fortify.ssc.restclient.model.RulepackCore;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Rulepack Core DTO object
 */
@ApiModel(description = "Rulepack Core DTO object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class RulepackCore {
  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rulepackGUID")
  private String rulepackGUID = null;

  /**
   * Gets or Sets rulepackType
   */
  @JsonAdapter(RulepackTypeEnum.Adapter.class)
  public enum RulepackTypeEnum {
    SCA("SCA"),
    
    RTA("RTA"),
    
    CATPACK("CATPACK");

    private String value;

    RulepackTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RulepackTypeEnum fromValue(String text) {
      for (RulepackTypeEnum b : RulepackTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RulepackTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RulepackTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RulepackTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RulepackTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("rulepackType")
  private RulepackTypeEnum rulepackType = null;

  @SerializedName("sku")
  private String sku = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("versions")
  private List<RulepackCore> versions = null;

  public RulepackCore description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RulepackCore id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public RulepackCore language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public RulepackCore locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @ApiModelProperty(value = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public RulepackCore name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RulepackCore rulepackGUID(String rulepackGUID) {
    this.rulepackGUID = rulepackGUID;
    return this;
  }

   /**
   * Get rulepackGUID
   * @return rulepackGUID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRulepackGUID() {
    return rulepackGUID;
  }

  public void setRulepackGUID(String rulepackGUID) {
    this.rulepackGUID = rulepackGUID;
  }

  public RulepackCore rulepackType(RulepackTypeEnum rulepackType) {
    this.rulepackType = rulepackType;
    return this;
  }

   /**
   * Get rulepackType
   * @return rulepackType
  **/
  @ApiModelProperty(required = true, value = "")
  public RulepackTypeEnum getRulepackType() {
    return rulepackType;
  }

  public void setRulepackType(RulepackTypeEnum rulepackType) {
    this.rulepackType = rulepackType;
  }

  public RulepackCore sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public RulepackCore version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public RulepackCore versions(List<RulepackCore> versions) {
    this.versions = versions;
    return this;
  }

  public RulepackCore addVersionsItem(RulepackCore versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<RulepackCore>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Get versions
   * @return versions
  **/
  @ApiModelProperty(value = "")
  public List<RulepackCore> getVersions() {
    return versions;
  }

  public void setVersions(List<RulepackCore> versions) {
    this.versions = versions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RulepackCore rulepackCore = (RulepackCore) o;
    return Objects.equals(this.description, rulepackCore.description) &&
        Objects.equals(this.id, rulepackCore.id) &&
        Objects.equals(this.language, rulepackCore.language) &&
        Objects.equals(this.locale, rulepackCore.locale) &&
        Objects.equals(this.name, rulepackCore.name) &&
        Objects.equals(this.rulepackGUID, rulepackCore.rulepackGUID) &&
        Objects.equals(this.rulepackType, rulepackCore.rulepackType) &&
        Objects.equals(this.sku, rulepackCore.sku) &&
        Objects.equals(this.version, rulepackCore.version) &&
        Objects.equals(this.versions, rulepackCore.versions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, language, locale, name, rulepackGUID, rulepackType, sku, version, versions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RulepackCore {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rulepackGUID: ").append(toIndentedString(rulepackGUID)).append("\n");
    sb.append("    rulepackType: ").append(toIndentedString(rulepackType)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

