/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.model;

import java.util.Objects;
import com.fortify.ssc.restclient.model.RulepacksBatchProcessStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Object represents rulepack processing status. This is readonly object.
 */
@ApiModel(description = "Object represents rulepack processing status. This is readonly object.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-09T13:54:27.094-07:00")
public class RulepacksBatchProcessStatus {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("statuses")
  private List<RulepacksBatchProcessStatus> statuses = null;

   /**
   * Numeric processing code.
   * @return code
  **/
  @ApiModelProperty(value = "Numeric processing code.")
  public Integer getCode() {
    return code;
  }

   /**
   * Processing message.
   * @return message
  **/
  @ApiModelProperty(value = "Processing message.")
  public String getMessage() {
    return message;
  }

  public RulepacksBatchProcessStatus statuses(List<RulepacksBatchProcessStatus> statuses) {
    this.statuses = statuses;
    return this;
  }

  public RulepacksBatchProcessStatus addStatusesItem(RulepacksBatchProcessStatus statusesItem) {
    if (this.statuses == null) {
      this.statuses = new ArrayList<RulepacksBatchProcessStatus>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * Child rulepacks processing statuses.
   * @return statuses
  **/
  @ApiModelProperty(value = "Child rulepacks processing statuses.")
  public List<RulepacksBatchProcessStatus> getStatuses() {
    return statuses;
  }

  public void setStatuses(List<RulepacksBatchProcessStatus> statuses) {
    this.statuses = statuses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RulepacksBatchProcessStatus rulepacksBatchProcessStatus = (RulepacksBatchProcessStatus) o;
    return Objects.equals(this.code, rulepacksBatchProcessStatus.code) &&
        Objects.equals(this.message, rulepacksBatchProcessStatus.message) &&
        Objects.equals(this.statuses, rulepacksBatchProcessStatus.statuses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, statuses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RulepacksBatchProcessStatus {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

