/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiCallback;
import com.fortify.ssc.restclient.ApiClient;
import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.ApiResponse;
import com.fortify.ssc.restclient.Configuration;
import com.fortify.ssc.restclient.Pair;
import com.fortify.ssc.restclient.ProgressRequestBody;
import com.fortify.ssc.restclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultListProjectVersionIssueDetails;
import com.fortify.ssc.restclient.model.ApiResultProjectVersionIssueDetails;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IssueDetailControllerApi {
    private ApiClient apiClient;

    public IssueDetailControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public IssueDetailControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for listIssueDetail
     * @param projectName projectName (required)
     * @param projectVersionName projectVersionName (required)
     * @param instanceId instanceId (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listIssueDetailCall(String projectName, String projectVersionName, String instanceId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/issueDetails";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (projectName != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("projectName", projectName));
        if (projectVersionName != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("projectVersionName", projectVersionName));
        if (instanceId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("instanceId", instanceId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "FortifyToken" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listIssueDetailValidateBeforeCall(String projectName, String projectVersionName, String instanceId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'projectName' is set
        if (projectName == null) {
            throw new ApiException("Missing the required parameter 'projectName' when calling listIssueDetail(Async)");
        }
        
        // verify the required parameter 'projectVersionName' is set
        if (projectVersionName == null) {
            throw new ApiException("Missing the required parameter 'projectVersionName' when calling listIssueDetail(Async)");
        }
        
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling listIssueDetail(Async)");
        }
        

        com.squareup.okhttp.Call call = listIssueDetailCall(projectName, projectVersionName, instanceId, progressListener, progressRequestListener);
        return call;

    }

    /**
     * list
     * 
     * @param projectName projectName (required)
     * @param projectVersionName projectVersionName (required)
     * @param instanceId instanceId (required)
     * @return ApiResultListProjectVersionIssueDetails
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResultListProjectVersionIssueDetails listIssueDetail(String projectName, String projectVersionName, String instanceId) throws ApiException {
        ApiResponse<ApiResultListProjectVersionIssueDetails> resp = listIssueDetailWithHttpInfo(projectName, projectVersionName, instanceId);
        return resp.getData();
    }

    /**
     * list
     * 
     * @param projectName projectName (required)
     * @param projectVersionName projectVersionName (required)
     * @param instanceId instanceId (required)
     * @return ApiResponse&lt;ApiResultListProjectVersionIssueDetails&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiResultListProjectVersionIssueDetails> listIssueDetailWithHttpInfo(String projectName, String projectVersionName, String instanceId) throws ApiException {
        com.squareup.okhttp.Call call = listIssueDetailValidateBeforeCall(projectName, projectVersionName, instanceId, null, null);
        Type localVarReturnType = new TypeToken<ApiResultListProjectVersionIssueDetails>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * list (asynchronously)
     * 
     * @param projectName projectName (required)
     * @param projectVersionName projectVersionName (required)
     * @param instanceId instanceId (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listIssueDetailAsync(String projectName, String projectVersionName, String instanceId, final ApiCallback<ApiResultListProjectVersionIssueDetails> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listIssueDetailValidateBeforeCall(projectName, projectVersionName, instanceId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiResultListProjectVersionIssueDetails>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for readIssueDetail
     * @param id id (required)
     * @param filterset Filter set to use (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call readIssueDetailCall(Long id, String filterset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/issueDetails/{id}"
            .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (filterset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filterset", filterset));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "FortifyToken" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call readIssueDetailValidateBeforeCall(Long id, String filterset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling readIssueDetail(Async)");
        }
        

        com.squareup.okhttp.Call call = readIssueDetailCall(id, filterset, progressListener, progressRequestListener);
        return call;

    }

    /**
     * read
     * 
     * @param id id (required)
     * @param filterset Filter set to use (optional)
     * @return ApiResultProjectVersionIssueDetails
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResultProjectVersionIssueDetails readIssueDetail(Long id, String filterset) throws ApiException {
        ApiResponse<ApiResultProjectVersionIssueDetails> resp = readIssueDetailWithHttpInfo(id, filterset);
        return resp.getData();
    }

    /**
     * read
     * 
     * @param id id (required)
     * @param filterset Filter set to use (optional)
     * @return ApiResponse&lt;ApiResultProjectVersionIssueDetails&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiResultProjectVersionIssueDetails> readIssueDetailWithHttpInfo(Long id, String filterset) throws ApiException {
        com.squareup.okhttp.Call call = readIssueDetailValidateBeforeCall(id, filterset, null, null);
        Type localVarReturnType = new TypeToken<ApiResultProjectVersionIssueDetails>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * read (asynchronously)
     * 
     * @param id id (required)
     * @param filterset Filter set to use (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call readIssueDetailAsync(Long id, String filterset, final ApiCallback<ApiResultProjectVersionIssueDetails> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = readIssueDetailValidateBeforeCall(id, filterset, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiResultProjectVersionIssueDetails>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
