/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultDynamicScanRequest;
import com.fortify.ssc.restclient.model.ApiResultListDynamicScanRequest;
import com.fortify.ssc.restclient.model.ApiResultVoid;
import com.fortify.ssc.restclient.model.DynamicScanRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DynamicScanRequestOfProjectVersionControllerApi
 */
@Ignore
public class DynamicScanRequestOfProjectVersionControllerApiTest {

    private final DynamicScanRequestOfProjectVersionControllerApi api = new DynamicScanRequestOfProjectVersionControllerApi();

    
    /**
     * Cancel a Dynamic Scan Request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelDynamicScanRequestOfProjectVersionTest() throws ApiException {
        Long id = null;
        ApiResultVoid response = api.cancelDynamicScanRequestOfProjectVersion(id);

        // TODO: test validations
    }
    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDynamicScanRequestOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        DynamicScanRequest resource = null;
        ApiResultDynamicScanRequest response = api.createDynamicScanRequestOfProjectVersion(parentId, resource);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDynamicScanRequestOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        String fields = null;
        ApiResultListDynamicScanRequest response = api.listDynamicScanRequestOfProjectVersion(parentId, fields);

        // TODO: test validations
    }
    
    /**
     * read
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readDynamicScanRequestOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        Long id = null;
        String fields = null;
        ApiResultDynamicScanRequest response = api.readDynamicScanRequestOfProjectVersion(parentId, id, fields);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDynamicScanRequestOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        Long id = null;
        DynamicScanRequest resource = null;
        ApiResultDynamicScanRequest response = api.updateDynamicScanRequestOfProjectVersion(parentId, id, resource);

        // TODO: test validations
    }
    
}
