/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultIIDMigration;
import com.fortify.ssc.restclient.model.ApiResultListIIDMigration;
import com.fortify.ssc.restclient.model.IIDMigration;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IidMigrationOfProjectVersionControllerApi
 */
@Ignore
public class IidMigrationOfProjectVersionControllerApiTest {

    private final IidMigrationOfProjectVersionControllerApi api = new IidMigrationOfProjectVersionControllerApi();

    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createIidMigrationOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        IIDMigration data = null;
        ApiResultIIDMigration response = api.createIidMigrationOfProjectVersion(parentId, data);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listIidMigrationOfProjectVersionTest() throws ApiException {
        Long parentId = null;
        String fields = null;
        ApiResultListIIDMigration response = api.listIidMigrationOfProjectVersion(parentId, fields);

        // TODO: test validations
    }
    
}
