/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.model.ApiCollectionActionlong;
import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultApiActionResponse;
import com.fortify.ssc.restclient.model.ApiResultCloudPoolProjectVersionActionResponse;
import com.fortify.ssc.restclient.model.ApiResultListProjectVersion;
import com.fortify.ssc.restclient.model.CloudPoolProjectVersionAssignRequest;
import com.fortify.ssc.restclient.model.CloudPoolProjectVersionReplaceRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectVersionOfCloudPoolControllerApi
 */
@Ignore
public class ProjectVersionOfCloudPoolControllerApiTest {

    private final ProjectVersionOfCloudPoolControllerApi api = new ProjectVersionOfCloudPoolControllerApi();

    
    /**
     * assign
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void assignProjectVersionOfCloudPoolTest() throws ApiException {
        String parentId = null;
        CloudPoolProjectVersionAssignRequest resource = null;
        ApiResultCloudPoolProjectVersionActionResponse response = api.assignProjectVersionOfCloudPool(parentId, resource);

        // TODO: test validations
    }
    
    /**
     * doAction
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doActionProjectVersionOfCloudPoolTest() throws ApiException {
        String parentId = null;
        ApiCollectionActionlong collectionAction = null;
        ApiResultApiActionResponse response = api.doActionProjectVersionOfCloudPool(parentId, collectionAction);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProjectVersionOfCloudPoolTest() throws ApiException {
        String parentId = null;
        String fields = null;
        Integer start = null;
        Integer limit = null;
        String orderby = null;
        ApiResultListProjectVersion response = api.listProjectVersionOfCloudPool(parentId, fields, start, limit, orderby);

        // TODO: test validations
    }
    
    /**
     * replace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceProjectVersionOfCloudPoolTest() throws ApiException {
        String parentId = null;
        CloudPoolProjectVersionReplaceRequest resource = null;
        ApiResultCloudPoolProjectVersionActionResponse response = api.replaceProjectVersionOfCloudPool(parentId, resource);

        // TODO: test validations
    }
    
}
