/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultListRole;
import com.fortify.ssc.restclient.model.ApiResultRole;
import com.fortify.ssc.restclient.model.ApiResultVoid;
import com.fortify.ssc.restclient.model.Role;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoleControllerApi
 */
@Ignore
public class RoleControllerApiTest {

    private final RoleControllerApi api = new RoleControllerApi();

    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRoleTest() throws ApiException {
        Role resource = null;
        ApiResultRole response = api.createRole(resource);

        // TODO: test validations
    }
    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRoleTest() throws ApiException {
        String id = null;
        ApiResultVoid response = api.deleteRole(id);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listRoleTest() throws ApiException {
        Integer start = null;
        Integer limit = null;
        String q = null;
        String orderby = null;
        String fields = null;
        Boolean excludeuseronly = null;
        ApiResultListRole response = api.listRole(start, limit, q, orderby, fields, excludeuseronly);

        // TODO: test validations
    }
    
    /**
     * multiDelete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void multiDeleteRoleTest() throws ApiException {
        String ids = null;
        ApiResultVoid response = api.multiDeleteRole(ids);

        // TODO: test validations
    }
    
    /**
     * read
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readRoleTest() throws ApiException {
        String id = null;
        String fields = null;
        ApiResultRole response = api.readRole(id, fields);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRoleTest() throws ApiException {
        String id = null;
        Role resource = null;
        ApiResultRole response = api.updateRole(id, resource);

        // TODO: test validations
    }
    
}
