/*
 * Fortify Software Security Center API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1:18.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fortify.ssc.restclient.api;

import com.fortify.ssc.restclient.ApiException;
import com.fortify.ssc.restclient.model.ApiResult;
import com.fortify.ssc.restclient.model.ApiResultValidationStatus;
import com.fortify.ssc.restclient.model.ValidationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ValidateSearchStringControllerApi
 */
@Ignore
public class ValidateSearchStringControllerApiTest {

    private final ValidateSearchStringControllerApi api = new ValidateSearchStringControllerApi();

    
    /**
     * DoValidation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doValidateSearchStringTest() throws ApiException {
        ValidationRequest request = null;
        ApiResultValidationStatus response = api.doValidateSearchString(request);

        // TODO: test validations
    }
    
}
